-- MySQL Script generated by MySQL Workbench
-- 01/18/19 10:12:35
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema TuSalud
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TuSalud
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TuSalud` DEFAULT CHARACTER SET utf8 ;
USE `TuSalud` ;

-- -----------------------------------------------------
-- Table `TuSalud`.`Cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TuSalud`.`Cuenta` (
  `id` INT(225) NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

INSERT INTO `TuSalud`.`Cuenta` (id, usuario, contraseña) Values (2, 'ManuSaponte', '25872099');
INSERT INTO `TuSalud`.`Cuenta` (id, usuario, contraseña) Values (3, 'RodrigoPerez', '3411112');
INSERT INTO `TuSalud`.`Cuenta` (id, usuario, contraseña) Values (4, 'Franchesco', '95786234');
INSERT INTO `TuSalud`.`Cuenta` (id, usuario, contraseña) Values (5, 'Mariano', '78345986');
INSERT INTO `TuSalud`.`Cuenta` (id, usuario, contraseña) Values (6, 'MathMurdok', '88769236');
INSERT INTO `TuSalud`.`Cuenta` (id, usuario, contraseña) Values (7, 'Pepito123', '97994100');
INSERT INTO `TuSalud`.`Cuenta` (id, usuario, contraseña) Values (8, 'MaclomGraves', '34567810');
INSERT INTO `TuSalud`.`Cuenta` (id, usuario, contraseña) Values (9, 'DarudeSandstorm', '11223345');
INSERT INTO `TuSalud`.`Cuenta` (id, usuario, contraseña) Values (10, 'MarucioMacri', '3456789');
INSERT INTO `TuSalud`.`Cuenta` (id, usuario, contraseña) Values (11, 'Movediza123', '3456810');
INSERT INTO `TuSalud`.`Cuenta` (id, usuario, contraseña) Values (12, 'Marianela4', '3453490');
INSERT INTO `TuSalud`.`Cuenta` (id, usuario, contraseña) Values (13, 'ModoDiabo', 'Skere');
INSERT INTO `TuSalud`.`Cuenta` (id, usuario, contraseña) Values (14, 'Ortencia', 'Ortencia');
INSERT INTO `TuSalud`.`Cuenta` (id, usuario, contraseña) Values (15, 'Army', 'BTS1234');

SELECT * FROM `TuSalud`.`Cuenta` 
-- -----------------------------------------------------
-- Table `TuSalud`.`Direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TuSalud`.`Direccion` (
  `id` INT(225) NOT NULL AUTO_INCREMENT,
  `numero` INT(225) NOT NULL,
  `calle` VARCHAR(45) NOT NULL,
  `piso` INT(225) NULL,
  `departamento` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `TuSalud`.`Lugar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TuSalud`.`Lugar` (
  `id` INT(225) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `id_Direccion` INT(225) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Lugar_Direccion1_idx` (`id_Direccion` ASC),
  CONSTRAINT `fk_Lugar_Direccion1`
    FOREIGN KEY (`id_Direccion`)
    REFERENCES `TuSalud`.`Direccion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TuSalud`.`Paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TuSalud`.`Paciente` (
  `id` INT(225) NOT NULL AUTO_INCREMENT,
  `historia_clinica` INT(225) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefono` LONG NOT NULL,
  `id_Lugar` INT(225) NOT NULL,
  `id_Direccion` INT(225) NULL,
  `id_Cuenta` INT(225) NOT NULL,
  `observaciones` VARCHAR(1024) NULL,
  INDEX `fk_Pasiente_Lugar1_idx` (`id_Lugar` ASC),
  INDEX `fk_Pasiente_Direccion1_idx` (`id_Direccion` ASC),
  INDEX `fk_Pasiente_Usuario1_idx` (`id_Cuenta` ASC),
  UNIQUE INDEX `historia_clinica_UNIQUE` (`historia_clinica` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Pasiente_Lugar1`
    FOREIGN KEY (`id_Lugar`)
    REFERENCES `TuSalud`.`Lugar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pasiente_Direccion1`
    FOREIGN KEY (`id_Direccion`)
    REFERENCES `TuSalud`.`Direccion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pasiente_Usuario1`
    FOREIGN KEY (`id_Cuenta`)
    REFERENCES `TuSalud`.`Cuenta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO `TuSalud`.`Paciente` (id, historia_clinica, nombre, apellido, email, telefono, id_lugar, id_direccion, id_cuenta, observaciones) Values (1, 1, Pablo, Andrade, pablo123_@hotmail.com, 249 349-9178, 1, 1 ,1, 'No tiene salvacion');
INSERT INTO `TuSalud`.`Paciente` (id, historia_clinica, nombre, apellido, email, telefono, id_lugar, id_direccion, id_cuenta, observaciones) Values (2, 2, Manuel, Saponte, Naru32_@hotmail.com, 249 246-6578, 2, 2 , 2, 'Le cuesta respirar');
INSERT INTO `TuSalud`.`Paciente` (id, historia_clinica, nombre, apellido, email, telefono, id_lugar, id_direccion, id_cuenta, observaciones) Values (3, 3, Pablo, Andrade, pablo123_@hotmail.com, 249 349-9178, 1, 1 ,1, 'No tiene salvacion');
INSERT INTO `TuSalud`.`Paciente` (id, historia_clinica, nombre, apellido, email, telefono, id_lugar, id_direccion, id_cuenta, observaciones) Values (4, 4, Pablo, Andrade, pablo123_@hotmail.com, 249 349-9178, 1, 1 ,1, 'No tiene salvacion');
INSERT INTO `TuSalud`.`Paciente` (id, historia_clinica, nombre, apellido, email, telefono, id_lugar, id_direccion, id_cuenta, observaciones) Values (5, 5, Pablo, Andrade, pablo123_@hotmail.com, 249 349-9178, 1, 1 ,1, 'No tiene salvacion');
INSERT INTO `TuSalud`.`Paciente` (id, historia_clinica, nombre, apellido, email, telefono, id_lugar, id_direccion, id_cuenta, observaciones) Values (6, 6, Pablo, Andrade, pablo123_@hotmail.com, 249 349-9178, 1, 1 ,1, 'No tiene salvacion');
INSERT INTO `TuSalud`.`Paciente` (id, historia_clinica, nombre, apellido, email, telefono, id_lugar, id_direccion, id_cuenta, observaciones) Values (7, 7, Pablo, Andrade, pablo123_@hotmail.com, 249 349-9178, 1, 1 ,1, 'No tiene salvacion');
INSERT INTO `TuSalud`.`Paciente` (id, historia_clinica, nombre, apellido, email, telefono, id_lugar, id_direccion, id_cuenta, observaciones) Values (8, 8, Pablo, Andrade, pablo123_@hotmail.com, 249 349-9178, 1, 1 ,1, 'No tiene salvacion');
INSERT INTO `TuSalud`.`Paciente` (id, historia_clinica, nombre, apellido, email, telefono, id_lugar, id_direccion, id_cuenta, observaciones) Values (9, 9, Pablo, Andrade, pablo123_@hotmail.com, 249 349-9178, 1, 1 ,1, 'No tiene salvacion');
INSERT INTO `TuSalud`.`Paciente` (id, historia_clinica, nombre, apellido, email, telefono, id_lugar, id_direccion, id_cuenta, observaciones) Values (10, 10, Pablo, Andrade, pablo123_@hotmail.com, 249 349-9178, 1, 1 ,1, 'No tiene salvacion');

-- -----------------------------------------------------
-- Table `TuSalud`.`Familiar_a_cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TuSalud`.`Familiar_a_cargo` (
  `id` INT(225) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `id_Paciente` INT(225) NOT NULL,
  `mi_historia_clinica` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Familiar_a_cargo_Pasiente1_idx` (`id_Paciente` ASC),
  INDEX `fk_Familiar_a_cargo_Paciente2_idx` (`mi_historia_clinica` ASC),
  CONSTRAINT `fk_Familiar_a_cargo_Paciente1`
    FOREIGN KEY (`id_Paciente`)
    REFERENCES `TuSalud`.`Paciente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Familiar_a_cargo_Paciente2`
    FOREIGN KEY (`mi_historia_clinica`)
    REFERENCES `TuSalud`.`Paciente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TuSalud`.`Especialidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TuSalud`.`Especialidad` (
  `id` INT(225) NOT NULL AUTO_INCREMENT,
  `nombre_especialidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TuSalud`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TuSalud`.`Empleado` (
  `id` INT(225) NOT NULL AUTO_INCREMENT,
  `legajo_empleado` INT(225) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefono` LONG NOT NULL,
  `observaciones` VARCHAR(45) NOT NULL,
  `id_Cuenta` INT(225) NOT NULL,
  `id_Direccion` INT(225) NULL,
  `id_Lugar` INT(225) NOT NULL,
  INDEX `fk_Empleado_Usuario1_idx` (`id_Cuenta` ASC),
  INDEX `fk_Empleado_Direccion1_idx` (`id_Direccion` ASC),
  INDEX `fk_Empleado_Lugar1_idx` (`id_Lugar` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Empleado_Usuario1`
    FOREIGN KEY (`id_Cuenta`)
    REFERENCES `TuSalud`.`Cuenta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empleado_Direccion1`
    FOREIGN KEY (`id_Direccion`)
    REFERENCES `TuSalud`.`Direccion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empleado_Lugar1`
    FOREIGN KEY (`id_Lugar`)
    REFERENCES `TuSalud`.`Lugar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TuSalud`.`Turno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TuSalud`.`Turno` (
  `id` INT(225) NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME(6) NOT NULL,
  `libre` BIT(1) NOT NULL,
  `id_Lugar` INT(225) NOT NULL,
  `id_Especialidad` INT(225) NOT NULL,
  `id_Paciente` INT(225) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Turno_Lugar1_idx` (`id_Lugar` ASC),
  INDEX `fk_Turno_Especialidad1_idx` (`id_Especialidad` ASC),
  INDEX `fk_Turno_Pasiente1_idx` (`id_Paciente` ASC),
  CONSTRAINT `fk_Turno_Lugar1`
    FOREIGN KEY (`id_Lugar`)
    REFERENCES `TuSalud`.`Lugar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Turno_Especialidad1`
    FOREIGN KEY (`id_Especialidad`)
    REFERENCES `TuSalud`.`Especialidad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Turno_Pasiente1`
    FOREIGN KEY (`id_Paciente`)
    REFERENCES `TuSalud`.`Paciente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TuSalud`.`Derivacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TuSalud`.`Derivacion` (
  `id` INT(225) NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `aprobado` BIT(1) NOT NULL,
  `id_Especialidad` INT(225) NOT NULL,
  `id_Paciente` INT(225) NOT NULL,
  INDEX `fk_Derivacion_Especialidad1_idx` (`id_Especialidad` ASC),
  PRIMARY KEY (`id`),
  INDEX `fk_Derivacion_Paciente1_idx` (`id_Paciente` ASC),
  CONSTRAINT `fk_Derivacion_Especialidad1`
    FOREIGN KEY (`id_Especialidad`)
    REFERENCES `TuSalud`.`Especialidad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Derivacion_Paciente1`
    FOREIGN KEY (`id_Paciente`)
    REFERENCES `TuSalud`.`Paciente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TuSalud`.`Lugar_nn_Especialidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TuSalud`.`Lugar_nn_Especialidad` (
  `id_Lugar` INT(225) NOT NULL,
  `id_Especialidad` INT(225) NOT NULL,
  PRIMARY KEY (`id_Lugar`, `id_Especialidad`),
  INDEX `fk_Lugar_nn_Especialidad_Especialidad1_idx` (`id_Especialidad` ASC),
  INDEX `fk_Lugar_nn_Especialidad_Lugar1_idx` (`id_Lugar` ASC),
  CONSTRAINT `fk_Lugar_nn_Especialidad_Lugar1`
    FOREIGN KEY (`id_Lugar`)
    REFERENCES `TuSalud`.`Lugar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Lugar_nn_Especialidad_Especialidad1`
    FOREIGN KEY (`id_Especialidad`)
    REFERENCES `TuSalud`.`Especialidad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TuSalud`.`Profesional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TuSalud`.`Profesional` (
  `id` INT(225) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `id_Especialidad` INT(225) NOT NULL,
  INDEX `fk_Profesional_Especialidad1_idx` (`id_Especialidad` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Profesional_Especialidad1`
    FOREIGN KEY (`id_Especialidad`)
    REFERENCES `TuSalud`.`Especialidad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TuSalud`.`Turno_nn_Profesional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TuSalud`.`Turno_nn_Profesional` (
  `Turno_id` INT(225) NOT NULL,
  `Profesional_id` INT(225) NOT NULL,
  PRIMARY KEY (`Turno_id`, `Profesional_id`),
  INDEX `fk_Turno_nn_Profesional_Profesional1_idx` (`Profesional_id` ASC),
  INDEX `fk_Turno_nn_Profesional_Turno1_idx` (`Turno_id` ASC),
  CONSTRAINT `fk_Turno_nn_Profesional_Turno1`
    FOREIGN KEY (`Turno_id`)
    REFERENCES `TuSalud`.`Turno` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Turno_nn_Profesional_Profesional1`
    FOREIGN KEY (`Profesional_id`)
    REFERENCES `TuSalud`.`Profesional` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

insert into cuenta(usuario, contraseña)
values ("Pablo",1234);

insert into direccion(numero, calle, piso, departamento)
values (124, "belgrano", 1 , 1);

insert into lugar(nombre, id_Direccion)
values ("clinica", 1);

insert into empleado(legajo_empleado, nombre, apellido, email, telefono, observaciones, id_Direccion, id_Cuenta, id_Lugar)
values (5, "Juan", "Perez", "empleado@gmail.com", 2494778899, "nada", 1, 1, 1);