-- MySQL Script generated by MySQL Workbench
-- 01/18/19 10:12:35
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
DROP SCHEMA IF EXISTS `TuSalud`;

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema TuSalud
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TuSalud
-- -----------------------------------------------------

CREATE SCHEMA IF NOT EXISTS `TuSalud` DEFAULT CHARACTER SET utf8 ;
USE `TuSalud` ;

-- -----------------------------------------------------
-- Table `TuSalud`.`Cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TuSalud`.`Cuenta` (
  `id` INT(225) NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

INSERT INTO `TuSalud`.`Cuenta` (id, usuario, contraseña) values ( 'Pablo', '23409877');
INSERT INTO `TuSalud`.`Cuenta` (id, usuario, contraseña) Values ( 'Manu', '25872099');
INSERT INTO `TuSalud`.`Cuenta` (id, usuario, contraseña) Values ( 'Rodrigo', '3411112');
INSERT INTO `TuSalud`.`Cuenta` (id, usuario, contraseña) Values ( 'Franchesco', '95786234');
INSERT INTO `TuSalud`.`Cuenta` (id, usuario, contraseña) Values ( 'Mariano', '78345986');
INSERT INTO `TuSalud`.`Cuenta` (id, usuario, contraseña) Values ( 'Mati', '88769236');
INSERT INTO `TuSalud`.`Cuenta` (id, usuario, contraseña) Values ( 'Pepito', '97994100');
INSERT INTO `TuSalud`.`Cuenta` (id, usuario, contraseña) Values ( 'Graves', '34567810');
INSERT INTO `TuSalud`.`Cuenta` (id, usuario, contraseña) Values ( 'Daniela', '11223345');
INSERT INTO `TuSalud`.`Cuenta` (id, usuario, contraseña) Values ( 'Marucio', '3456789');
INSERT INTO `TuSalud`.`Cuenta` (id, usuario, contraseña) Values ( 'Esther', '3456810');
INSERT INTO `TuSalud`.`Cuenta` (id, usuario, contraseña) Values ( 'Andrea', '3453490');
INSERT INTO `TuSalud`.`Cuenta` (id, usuario, contraseña) Values ( 'Catalina', '5466213');
INSERT INTO `TuSalud`.`Cuenta` (id, usuario, contraseña) Values ( 'Ortencia', '');
INSERT INTO `TuSalud`.`Cuenta` (id, usuario, contraseña) Values ( 'Florencia', '');

SELECT * FROM `TuSalud`.`Cuenta`;

-- -----------------------------------------------------
-- Table `TuSalud`.`Direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TuSalud`.`Direccion` (
  `id` INT(225) NOT NULL AUTO_INCREMENT,
  `numero` INT(225) NOT NULL,
  `calle` VARCHAR(45) NOT NULL,
  `piso` INT(225) NULL,
  `departamento` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

INSERT INTO  direccion (numero, calle, piso, departamento) values (125, 'sarmiento', 3, NULL);
INSERT INTO  direccion (numero, calle, piso, departamento) values (554, '9 de Julio', 2, NULL);
INSERT INTO  direccion (numero, calle, piso, departamento) values (1230, 'Doering', 1, NULL);
INSERT INTO  direccion (numero, calle, piso, departamento) values (223, '11 de Septiembre', 2, NULL);
INSERT INTO  direccion (numero, calle, piso, departamento) values (365, 'Grl.Paz', 1, NULL);
INSERT INTO  direccion (numero, calle, piso, departamento) values (765, 'misiones', 0, null);
INSERT INTO  direccion (numero, calle, piso, departamento) values (65, 'alem', 0, null);
INSERT INTO  direccion (numero, calle, piso, departamento) values (120, 'Brasil', 2, null);
INSERT INTO  direccion (numero, calle, piso, departamento) values (98, 'Avellaneda', 0, null);

SELECT * FROM `TuSalud`.`Direccion`;

DROP TABLE direccion;
-- -----------------------------------------------------
-- Table `TuSalud`.`Lugar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TuSalud`.`Lugar` (
  `id` INT(225) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `id_Direccion` INT(225) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Lugar_Direccion1_idx` (`id_Direccion` ASC),
  CONSTRAINT `fk_Lugar_Direccion1`
    FOREIGN KEY (`id_Direccion`)
    REFERENCES `TuSalud`.`Direccion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO Lugar (nombre, id_Direccion) values ('salita', 1);
INSERT INTO Lugar (nombre, id_Direccion) values ('salita2', 2);
INSERT INTO Lugar (nombre, id_Direccion) values ('salita3', 3);
INSERT INTO Lugar (nombre, id_Direccion) values ('salita4', 4);
INSERT INTO Lugar (nombre, id_Direccion) values ('salita5', 5);

SELECT * FROM lugar;

DROP TABLE lugar;
-- -----------------------------------------------------
-- Table `TuSalud`.`Paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TuSalud`.`Paciente` (
  `id` INT(225) NOT NULL AUTO_INCREMENT,
  `historia_clinica` INT(225) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefono` LONG NOT NULL,
  `id_Lugar` INT(225) NOT NULL,
  `id_Direccion` INT(225) NULL,
  `id_Cuenta` INT(225) NOT NULL,
  `observaciones` VARCHAR(1024) NULL,
  INDEX `fk_Pasiente_Lugar1_idx` (`id_Lugar` ASC),
  INDEX `fk_Pasiente_Direccion1_idx` (`id_Direccion` ASC),
  INDEX `fk_Pasiente_Usuario1_idx` (`id_Cuenta` ASC),
  UNIQUE INDEX `historia_clinica_UNIQUE` (`historia_clinica` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Pasiente_Lugar1`
    FOREIGN KEY (`id_Lugar`)
    REFERENCES `TuSalud`.`Lugar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pasiente_Direccion1`
    FOREIGN KEY (`id_Direccion`)
    REFERENCES `TuSalud`.`Direccion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pasiente_Usuario1`
    FOREIGN KEY (`id_Cuenta`)
    REFERENCES `TuSalud`.`Cuenta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO  Paciente ( historia_clinica, nombre, apellido, email, telefono, id_Lugar, id_direccion, id_cuenta, observaciones) Values ( 1, 'Pablo', 'Andrade', 'pablo123_@hotmail.com', '249 349-9178', 1, NULL ,1, NULL);
INSERT INTO  Paciente ( historia_clinica, nombre, apellido, email, telefono, id_lugar, id_direccion, id_cuenta, observaciones) Values ( 2, 'Manuel', 'Saponte', 'Naru32_@hotmail.com', '249 246-6578', 2, NULL , 2, NULL);
INSERT INTO  Paciente ( historia_clinica, nombre, apellido, email, telefono, id_lugar, id_direccion, id_cuenta, observaciones) Values ( 3, 'Rodrigo', 'Perez', 'rodri_@gmail.com', '249 349-4128', 1, NULL ,3, NULL);
INSERT INTO  Paciente ( historia_clinica, nombre, apellido, email, telefono, id_lugar, id_direccion, id_cuenta, observaciones) Values ( 4, 'Francisco', 'Castillo', 'curva_@hotmail.com', '249 349-9178', 3, 7 ,4, NULL);
INSERT INTO  Paciente ( historia_clinica, nombre, apellido, email, telefono, id_lugar, id_direccion, id_cuenta, observaciones) Values ( 5, 'Mariano', 'Maceratti', 'Maruhapro_@gmail.com', '249 849-6778', 5, 6 ,5, NULL);
INSERT INTO  Paciente ( historia_clinica, nombre, apellido, email, telefono, id_lugar, id_direccion, id_cuenta, observaciones) Values ( 6, 'Mati', 'Serrano', 'WhiteMati_@hotmail.com', '249 123-0976', 2, NULL ,6, NULL);
INSERT INTO  Paciente ( historia_clinica, nombre, apellido, email, telefono, id_lugar, id_direccion, id_cuenta, observaciones) Values ( 7, 'Pedro', 'Serrano', 'AmericanPedro@hotmail.com', '249 961-4438', 1, NULL ,7, NULL);
INSERT INTO  Paciente ( historia_clinica, nombre, apellido, email, telefono, id_lugar, id_direccion, id_cuenta, observaciones) Values ( 8, 'Malcom', 'Graves', 'Destino@gmail.com', '249 341-9135', 3, NULL ,8, NULL);
INSERT INTO  Paciente ( historia_clinica, nombre, apellido, email, telefono, id_lugar, id_direccion, id_cuenta, observaciones) Values ( 9, 'Daniela', 'Guerra', 'pablo123_@hotmail.com', '249 349-9178', 1, 8 ,9, NULL);
INSERT INTO  Paciente ( historia_clinica, nombre, apellido, email, telefono, id_lugar, id_direccion, id_cuenta, observaciones) Values ( 10, 'Esther', 'Gonzales', 'pablo123_@hotmail.com', '249 349-9178', 1, 9 ,10, NULL);

DROP TABLE paciente;

SELECT * FROM `TuSalud`.`Paciente`;
-- -----------------------------------------------------
-- Table `TuSalud`.`Familiar_a_cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TuSalud`.`Familiar_a_cargo` (
  `id` INT(225) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `id_Paciente` INT(225) NOT NULL,
  `mi_historia_clinica` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Familiar_a_cargo_Pasiente1_idx` (`id_Paciente` ASC),
  INDEX `fk_Familiar_a_cargo_Paciente2_idx` (`mi_historia_clinica` ASC),
  CONSTRAINT `fk_Familiar_a_cargo_Paciente1`
    FOREIGN KEY (`id_Paciente`)
    REFERENCES `TuSalud`.`Paciente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Familiar_a_cargo_Paciente2`
    FOREIGN KEY (`mi_historia_clinica`)
    REFERENCES `TuSalud`.`Paciente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO familiar_a_cargo (nombre, apellido, id_paciente, mi_historia_clinica) values ('Daniel', 'Maceratti', 5, 5);
INSERT INTO familiar_a_cargo (nombre, apellido, id_paciente, mi_historia_clinica) values ('Adrian', 'Guerra', 9, 9);
INSERT INTO familiar_a_cargo (nombre, apellido, id_paciente, mi_historia_clinica) values ('Samuel', 'Perez', 3, 3);

SELECT * FROM familiar_a_cargo;
-- -----------------------------------------------------
-- Table `TuSalud`.`Especialidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TuSalud`.`Especialidad` (
  `id` INT(225) NOT NULL AUTO_INCREMENT,
  `nombre_especialidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TuSalud`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TuSalud`.`Empleado` (
  `id` INT(225) NOT NULL AUTO_INCREMENT,
  `legajo_empleado` INT(225) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefono` LONG NOT NULL,
  `observaciones` VARCHAR(45) NOT NULL,
  `id_Cuenta` INT(225) NOT NULL,
  `id_Direccion` INT(225) NULL,
  `id_Lugar` INT(225) NOT NULL,
  INDEX `fk_Empleado_Usuario1_idx` (`id_Cuenta` ASC),
  INDEX `fk_Empleado_Direccion1_idx` (`id_Direccion` ASC),
  INDEX `fk_Empleado_Lugar1_idx` (`id_Lugar` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Empleado_Usuario1`
    FOREIGN KEY (`id_Cuenta`)
    REFERENCES `TuSalud`.`Cuenta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empleado_Direccion1`
    FOREIGN KEY (`id_Direccion`)
    REFERENCES `TuSalud`.`Direccion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empleado_Lugar1`
    FOREIGN KEY (`id_Lugar`)
    REFERENCES `TuSalud`.`Lugar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TuSalud`.`Turno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TuSalud`.`Turno` (
  `id` INT(225) NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME(6) NOT NULL,
  `libre` BIT(1) NOT NULL,
  `id_Lugar` INT(225) NOT NULL,
  `id_Especialidad` INT(225) NOT NULL,
  `id_Paciente` INT(225) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Turno_Lugar1_idx` (`id_Lugar` ASC),
  INDEX `fk_Turno_Especialidad1_idx` (`id_Especialidad` ASC),
  INDEX `fk_Turno_Pasiente1_idx` (`id_Paciente` ASC),
  CONSTRAINT `fk_Turno_Lugar1`
    FOREIGN KEY (`id_Lugar`)
    REFERENCES `TuSalud`.`Lugar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Turno_Especialidad1`
    FOREIGN KEY (`id_Especialidad`)
    REFERENCES `TuSalud`.`Especialidad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Turno_Pasiente1`
    FOREIGN KEY (`id_Paciente`)
    REFERENCES `TuSalud`.`Paciente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TuSalud`.`Derivacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TuSalud`.`Derivacion` (
  `id` INT(225) NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `aprobado` BIT(1) NOT NULL,
  `id_Especialidad` INT(225) NOT NULL,
  `id_Paciente` INT(225) NOT NULL,
  INDEX `fk_Derivacion_Especialidad1_idx` (`id_Especialidad` ASC),
  PRIMARY KEY (`id`),
  INDEX `fk_Derivacion_Paciente1_idx` (`id_Paciente` ASC),
  CONSTRAINT `fk_Derivacion_Especialidad1`
    FOREIGN KEY (`id_Especialidad`)
    REFERENCES `TuSalud`.`Especialidad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Derivacion_Paciente1`
    FOREIGN KEY (`id_Paciente`)
    REFERENCES `TuSalud`.`Paciente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TuSalud`.`Lugar_nn_Especialidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TuSalud`.`Lugar_nn_Especialidad` (
  `id_Lugar` INT(225) NOT NULL,
  `id_Especialidad` INT(225) NOT NULL,
  PRIMARY KEY (`id_Lugar`, `id_Especialidad`),
  INDEX `fk_Lugar_nn_Especialidad_Especialidad1_idx` (`id_Especialidad` ASC),
  INDEX `fk_Lugar_nn_Especialidad_Lugar1_idx` (`id_Lugar` ASC),
  CONSTRAINT `fk_Lugar_nn_Especialidad_Lugar1`
    FOREIGN KEY (`id_Lugar`)
    REFERENCES `TuSalud`.`Lugar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Lugar_nn_Especialidad_Especialidad1`
    FOREIGN KEY (`id_Especialidad`)
    REFERENCES `TuSalud`.`Especialidad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TuSalud`.`Profesional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TuSalud`.`Profesional` (
  `id` INT(225) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `id_Especialidad` INT(225) NOT NULL,
  INDEX `fk_Profesional_Especialidad1_idx` (`id_Especialidad` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Profesional_Especialidad1`
    FOREIGN KEY (`id_Especialidad`)
    REFERENCES `TuSalud`.`Especialidad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TuSalud`.`Turno_nn_Profesional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TuSalud`.`Turno_nn_Profesional` (
  `Turno_id` INT(225) NOT NULL,
  `Profesional_id` INT(225) NOT NULL,
  PRIMARY KEY (`Turno_id`, `Profesional_id`),
  INDEX `fk_Turno_nn_Profesional_Profesional1_idx` (`Profesional_id` ASC),
  INDEX `fk_Turno_nn_Profesional_Turno1_idx` (`Turno_id` ASC),
  CONSTRAINT `fk_Turno_nn_Profesional_Turno1`
    FOREIGN KEY (`Turno_id`)
    REFERENCES `TuSalud`.`Turno` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Turno_nn_Profesional_Profesional1`
    FOREIGN KEY (`Profesional_id`)
    REFERENCES `TuSalud`.`Profesional` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

insert into cuenta(usuario, contraseña)
values ("Pablo",1234);

insert into direccion(numero, calle, piso, departamento)
values (124, "belgrano", 1 , 1);

insert into lugar(nombre, id_Direccion)
values ("clinica", 1);

insert into empleado(legajo_empleado, nombre, apellido, email, telefono, observaciones, id_Direccion, id_Cuenta, id_Lugar)
values (5, "Juan", "Perez", "empleado@gmail.com", 2494778899, "nada", 1, 1, 1);


DROP TABLE `TuSalud`.`Cuenta`
