/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.tusalud.interfacesEmpleado;

import com.mycompany.tusalud.controllerEmpleado.CrearTurnoController;
import com.mycompany.tusalud.data.Especialidad;
import com.mycompany.tusalud.data.Profesional;
import com.mycompany.tusalud.excepciones.BDException;
import com.mycompany.tusalud.excepciones.TuSaludException;
import com.mycompany.tusalud.interfaces.MiDialogo;
import java.sql.Time;
import java.time.LocalDate;
import java.util.Date;
import java.util.List;
import javax.swing.JComboBox;

/**
 *
 * @author Alumno
 */
public class VistaCrearTurno extends javax.swing.JFrame {

    CrearTurnoController crearTurnoController;
    private final List<Especialidad> listaDeEspecialidades;
    private final List<Profesional> listaDeProfesionales;
    private final LocalDate fechaSeleccionada;
    
    /**
     * Creates new form CrearTurno
     * @param crearTurnoController
     * @param listaDeEspecialidades
     * @param listaDeProfesionales
     * @param fechaSeleccionada
     */
    public VistaCrearTurno(CrearTurnoController crearTurnoController, List<Especialidad> listaDeEspecialidades, List<Profesional> listaDeProfesionales, LocalDate fechaSeleccionada) {
        this.crearTurnoController = crearTurnoController;
        this.listaDeEspecialidades = listaDeEspecialidades;
        this.listaDeProfesionales = listaDeProfesionales;
        this.fechaSeleccionada = fechaSeleccionada;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelHora = new javax.swing.JLabel();
        jLabelEspecialidad = new javax.swing.JLabel();
        jLabelProfecional = new javax.swing.JLabel();
        textHora = new javax.swing.JTextField();
        textMinutos = new javax.swing.JTextField();
        jcEspecialidad = new JComboBox(getArregloEspecialidad());
        jcProfesional = new JComboBox(getArreglodeProfesionales());
        jButtonGuardarTurno = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelHora.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelHora.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHora.setText("Hora");
        getContentPane().add(jLabelHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabelEspecialidad.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelEspecialidad.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEspecialidad.setText("Especialidad");
        getContentPane().add(jLabelEspecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabelProfecional.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelProfecional.setForeground(new java.awt.Color(255, 255, 255));
        jLabelProfecional.setText("Profecional");
        getContentPane().add(jLabelProfecional, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));
        getContentPane().add(textHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 25, -1));
        getContentPane().add(textMinutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 25, -1));
        getContentPane().add(jcEspecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 115, -1));
        getContentPane().add(jcProfesional, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 115, -1));

        jButtonGuardarTurno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonGuardarTurno.setText("Guardar Turno");
        jButtonGuardarTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarTurnoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGuardarTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, -1));

        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(":");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 10, 20));

        jPanel1.setBackground(new java.awt.Color(204, 153, 0));
        jPanel1.setForeground(new java.awt.Color(204, 153, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 60));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesL2/FondoListas.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuardarTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarTurnoActionPerformed
        try {
            guardarTurno();
        } catch (BDException ex) {
            MiDialogo.mostrar(ex, "Error");
        }
    }//GEN-LAST:event_jButtonGuardarTurnoActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        try {
            crearTurnoController.volverACargarCalendario(this);
        } catch (BDException ex) {
            MiDialogo.mostrar(ex, "Error al volver al calendario");
        }
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private String[] getArregloEspecialidad(){
        String[] arreglo = new String[listaDeEspecialidades.size()];
        
        for (int i=0; i<listaDeEspecialidades.size(); i++){
            arreglo[i] = listaDeEspecialidades.get(i).getNombre();
        }
        
        return arreglo;
    }
    
    private Especialidad getEspecialidadSeleccionada() {
        return listaDeEspecialidades.get(this.jcEspecialidad.getSelectedIndex());
    }
    
    private String[] getArreglodeProfesionales(){
        
        if(listaDeProfesionales != null){
            String[] arreglo = new String[listaDeProfesionales.size()];

            for (int i=0; i<listaDeProfesionales.size(); i++){
                arreglo[i] = listaDeProfesionales.get(i).getNombre() + " " + listaDeProfesionales.get(i).getApellido() + " | " + listaDeProfesionales.get(i).getEspecialidad().getNombre();
            }

            return arreglo;
        }
        else{
            return null;
        }
    }
    
    private Profesional getProfesionalSeleccionado() {
        if(this.jcProfesional.getSelectedIndex() != -1){
            return listaDeProfesionales.get(this.jcProfesional.getSelectedIndex());
        }
        else{
            return null;
        }
    }
    
    private void guardarTurno() throws BDException {
        try{
            Profesional profesional = null;
            Date fecha = java.sql.Date.valueOf(fechaSeleccionada);
            Time hora = new Time(new Integer(textHora.getText()), new Integer(textMinutos.getText()),0);
            Especialidad especialidad = getEspecialidadSeleccionada();

            if(getArreglodeProfesionales() != null){
                profesional = getProfesionalSeleccionado();
            }

            if((profesional != null) && (! especialidad.getNombre().equalsIgnoreCase(profesional.getEspecialidad().getNombre()) )){
                MiDialogo.mostrar("El profesional no trabaja con esta especialidad", "Error");
            }
            else{
                crearTurnoController.guardarTurno(especialidad, fecha, hora, profesional);
                crearTurnoController.volverACargarCalendario(this);
                MiDialogo.mostrar("El Turno fue creado con Exito", "Notificacion");
            }
        } catch(NumberFormatException e){
            MiDialogo.mostrar("La hora debe ser escrita en numeros", "Error");
        } catch (TuSaludException ex) {
            MiDialogo.mostrar(ex, "Error al crear el Turno");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonGuardarTurno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelEspecialidad;
    private javax.swing.JLabel jLabelHora;
    private javax.swing.JLabel jLabelProfecional;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jcEspecialidad;
    private javax.swing.JComboBox<String> jcProfesional;
    private javax.swing.JTextField textHora;
    private javax.swing.JTextField textMinutos;
    // End of variables declaration//GEN-END:variables
}
