/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.tusalud.interfacesEmpleado;

import com.mycompany.tusalud.controllerEmpleado.NotificacionesDePacienteController;
import com.mycompany.tusalud.data.Paciente;
import com.mycompany.tusalud.excepciones.BDException;
import com.mycompany.tusalud.interfaces.MiDialogo;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 *
 * @author Alumno
 */
public class VistaNotificacionesDePaciente extends javax.swing.JFrame {

    NotificacionesDePacienteController notificacionesDePacienteController;
    private Map<Integer, String> tablaBotonStringNotificacion = new HashMap<>();
    private Map<Integer, Integer> tablaBotonIdNotificacion = new HashMap<>();
    List<Object[]> lista;
    private Paciente paciente;
    
    /**
     * Creates new form VistaNotificacionesDePaciente
     * @param notificacionesDePacienteController
     * @param lista
     */
    public VistaNotificacionesDePaciente(NotificacionesDePacienteController notificacionesDePacienteController, List<Object[]> lista, Paciente paciente) {
        this.notificacionesDePacienteController = notificacionesDePacienteController;
        this.lista = lista;
        this.paciente = paciente;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonAñadirNotificacion = new javax.swing.JButton();
        jButtonEliminarTurno = new javax.swing.JButton();
        jButtonVerMensaje = new javax.swing.JButton();
        jButtonVolverASeleccionDePaciente = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            getMatrizObject(getArregloString().length),
            getArregloString()
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 610, 450));

        jButtonAñadirNotificacion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonAñadirNotificacion.setText("Anadir Notificacion");
        jButtonAñadirNotificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAñadirNotificacionActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAñadirNotificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 170, 180, -1));

        jButtonEliminarTurno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonEliminarTurno.setText("Eliminar Notificacion");
        jButtonEliminarTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarTurnoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEliminarTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(711, 220, 180, -1));

        jButtonVerMensaje.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonVerMensaje.setText("Ver Mensaje");
        jButtonVerMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerMensajeActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVerMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 340, 177, -1));

        jButtonVolverASeleccionDePaciente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonVolverASeleccionDePaciente.setText("Volver a Seleccion de Paciente");
        jButtonVolverASeleccionDePaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverASeleccionDePacienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVolverASeleccionDePaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 460, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Notificaciones de Paciente");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesL2/FondoListas.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setPreferredSize(new java.awt.Dimension(1000, 750));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAñadirNotificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAñadirNotificacionActionPerformed
        notificacionesDePacienteController.crearNotificacion(paciente, this);
    }//GEN-LAST:event_jButtonAñadirNotificacionActionPerformed

    private void jButtonVolverASeleccionDePacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverASeleccionDePacienteActionPerformed
        notificacionesDePacienteController.volverASeleccionarPaciente(this);
    }//GEN-LAST:event_jButtonVolverASeleccionDePacienteActionPerformed

    private void jButtonEliminarTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarTurnoActionPerformed
        Integer id = tablaBotonIdNotificacion.get(jTable1.getSelectedRow());
        try {
            if(id != null){
                notificacionesDePacienteController.eliminarNotificacion(paciente, id, this);
                MiDialogo.mostrar("Notificacion eliminada", "Notificacion");
            }
            else{
                System.out.println("No se ha seleccionado Notificacion");
            }
        } catch (BDException ex) {
            MiDialogo.mostrar(ex, "Error al eliminar la Notificacion");
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButtonEliminarTurnoActionPerformed

    private void jButtonVerMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerMensajeActionPerformed
        String mensaje = tablaBotonStringNotificacion.get(jTable1.getSelectedRow());
        if(mensaje != null){
            notificacionesDePacienteController.mostrarMensaje(mensaje);
        }
        else{
            System.out.println("No ha seleccionado notificacion");
        }
    }//GEN-LAST:event_jButtonVerMensajeActionPerformed

    private Object[][] getMatrizObject(Integer tamaño){
        Object[][] matriz = new Object[lista.size()][tamaño];
        
        for(int fila=0; fila<lista.size(); fila++){
            
            for(int columna=0; columna<tamaño; columna++){
                matriz[fila][columna] = lista.get(fila)[columna+1];
            }
            
            tablaBotonStringNotificacion.put(fila, (String) lista.get(fila)[3]);
            tablaBotonIdNotificacion.put(fila, (Integer) lista.get(fila)[0]);
        }
        
        return matriz;
    }
    
    private String[] getArregloString(){
        String[] arreglo = {"FechaVigenciaInicial", "FechaVigenciaFinal", "Texto"};
        
        return arreglo;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAñadirNotificacion;
    private javax.swing.JButton jButtonEliminarTurno;
    private javax.swing.JButton jButtonVerMensaje;
    private javax.swing.JButton jButtonVolverASeleccionDePaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
