/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.tusalud.interfacesEmpleado;

import com.mycompany.tusalud.controllerEmpleado.CalendarioCrearTurnoController;
import com.mycompany.tusalud.data.Turno;
import com.mycompany.tusalud.excepciones.BDException;
import com.mycompany.tusalud.interfaces.MiDialogo;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDate;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JFrame;

/**
 *
 * @author Alumno
 */
public class VistaCalendarioCrearTurno extends javax.swing.JFrame {

    CalendarioCrearTurnoController calendarioCrearTurnoController;
    private Map<Integer, LocalDate> tablaBotonFecha = new HashMap<>();
    private Map<Double, Turno> tablaBotonTurno = new HashMap<>();
    private List<Turno> lista;
    
    /**
     * Creates new form VistaCrearTurno
     * @param calendarioCrearTurnoController
     * @param lista
     */
    public VistaCalendarioCrearTurno(CalendarioCrearTurnoController calendarioCrearTurnoController, List<Turno> lista) {
        this.calendarioCrearTurnoController = calendarioCrearTurnoController;
        this.lista = lista;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabelInstruccion = new javax.swing.JLabel();
        jButtonVolverAMenu = new javax.swing.JButton();
        jButtonEliminarTurno = new javax.swing.JButton();
        jButtonAñadirTurno = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            getMatrizObject(getArregloLocalDate()),
            getArregloLocalDate()
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 854, 470));

        jLabelInstruccion.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelInstruccion.setText("Seleccione una fecha para añadir turnos");
        getContentPane().add(jLabelInstruccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 740, 60));

        jButtonVolverAMenu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonVolverAMenu.setText("Volver a menu");
        jButtonVolverAMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverAMenuActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVolverAMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 650, 170, 40));

        jButtonEliminarTurno.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonEliminarTurno.setText("Eliminar Turno");
        getContentPane().add(jButtonEliminarTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 650, 170, 40));

        jButtonAñadirTurno.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonAñadirTurno.setText("Añadir Turno");
        jButtonAñadirTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAñadirTurnoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAñadirTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 650, 170, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesL2/FondoListas.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 1000, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolverAMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverAMenuActionPerformed
         calendarioCrearTurnoController.volverAMenu(this);
    }//GEN-LAST:event_jButtonVolverAMenuActionPerformed

    private void jButtonAñadirTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAñadirTurnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAñadirTurnoActionPerformed

    private Object[][] getMatrizObject(LocalDate[] arreglo){
        Object[][] matriz = new Object[10][arreglo.length];
        int fila = 0;
        
        for(int columna=0; columna<arreglo.length; columna++){
                
            for(int indice=0; indice<lista.size(); indice++){
            
                if(lista.get(indice).getFecha().compareTo((java.sql.Date.valueOf(arreglo[columna]))) == 0){

                    matriz[fila][columna] = lista.get(indice).getHora().toLocalTime() + " | " + lista.get(indice).getEspecialidad().getNombre();
                    tablaBotonTurno.put(new Double(fila+"."+columna),lista.get(indice));
                    
                    fila = fila + 1;
                }
            }
            fila = 0;
        }
        
        jButtonAñadirTurno.addActionListener(listenerBotonCrearTurno);
        jButtonEliminarTurno.addActionListener(listenerBotonEliminarTurno);
        
        System.out.println(tablaBotonFecha);
        
        return matriz;
    }
    
    private LocalDate[] getArregloLocalDate(){
        LocalDate fecha = LocalDate.now();
        
        LocalDate[] arreglo = new LocalDate[5] ;
        
        for (int i=0;i<5;i++){
           arreglo[i] = fecha.plusDays(i);
           tablaBotonFecha.put(i, arreglo[i]);
        }
        
        return arreglo;
    }
    
    private ActionListener listenerBotonCrearTurno = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent ae) {
            LocalDate fechaSeleccionada = tablaBotonFecha.get(jTable1.getSelectedColumn());
            if (fechaSeleccionada != null){
                try {
                    calendarioCrearTurnoController.crearTurno(fechaSeleccionada, estaVentana());
                } catch (BDException ex) {
                    MiDialogo.mostrar("No se ha seleccionado fecha", "Mensaje");
                    ex.printStackTrace();
                }
            }
            else{
                System.out.println("No se ha seleccionado fecha");
            }
        }
    };
    
    private ActionListener listenerBotonEliminarTurno = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent ae) {
            Turno turno = (Turno) tablaBotonTurno.get(new Double(jTable1.getSelectedRow()+"."+jTable1.getSelectedColumn()));
            try {
                if(turno != null){
                    calendarioCrearTurnoController.eliminarTurno(turno, estaVentana());
                    MiDialogo.mostrar("Turno eliminado", "Notificacion");
                }
                else{
                    System.out.println("No se ha seleccionado turno");
                }
            } catch (BDException ex) {
                MiDialogo.mostrar(ex, "Error al eliminar el Turno");
                ex.printStackTrace();
            }
        }
    };

    public JFrame estaVentana(){
        return this;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAñadirTurno;
    private javax.swing.JButton jButtonEliminarTurno;
    private javax.swing.JButton jButtonVolverAMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelInstruccion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
