/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.tusalud.interfacesEmpleado;

import com.mycompany.tusalud.controllerEmpleado.ModificarDatosDePacienteController;
import com.mycompany.tusalud.data.Lugar;
import com.mycompany.tusalud.data.Paciente;
import com.mycompany.tusalud.excepciones.BDException;
import com.mycompany.tusalud.interfaces.MiDialogo;
import javax.swing.JComboBox;
import java.util.List;
import java.util.Objects;


/**
 *
 * @author Alumno
 */
public class VistaModificarDatosDePaciente extends javax.swing.JFrame {

    ModificarDatosDePacienteController modificarDatosDePacienteController;
    private Paciente paciente;
    private List<Lugar> lista;
    private int indice = 0;
    
    /**
     * Creates new form VistaModificarDatosDePaciente
     * @param paciente
     * @param modificarDatosDePacienteController
     * @param lista
     */
    public VistaModificarDatosDePaciente(ModificarDatosDePacienteController modificarDatosDePacienteController, Paciente paciente, List<Lugar> lista) {
        this.modificarDatosDePacienteController = modificarDatosDePacienteController;
        this.paciente = paciente;
        this.lista = lista;
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonVolverASeleccionarPaciente = new javax.swing.JButton();
        jButtonVolverAMenu = new javax.swing.JButton();
        jLabelNombre = new javax.swing.JLabel();
        jLabelApellido = new javax.swing.JLabel();
        jLabelTelefono = new javax.swing.JLabel();
        jLabelDireccion = new javax.swing.JLabel();
        jLabelLugarDesignado = new javax.swing.JLabel();
        jLabelNumero = new javax.swing.JLabel();
        jLabelPiso = new javax.swing.JLabel();
        jLabelDepto = new javax.swing.JLabel();
        jLabelHistoriaClinica = new javax.swing.JLabel();
        jLabelObservaciones = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaObservaciones = new javax.swing.JTextArea();
        jTextFieldHistoriaClinica = new javax.swing.JTextField();
        jTextFieldLugarDesignado = new javax.swing.JTextField();
        jTextFieldDireccion = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldTelefono = new javax.swing.JTextField();
        jTextFieldNumero = new javax.swing.JTextField();
        jTextFieldPiso = new javax.swing.JTextField();
        jTextFieldDepto = new javax.swing.JTextField();
        jTextFieldApellido = new javax.swing.JTextField();
        jButtonGuardar = new javax.swing.JButton();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jComboBoxLugares = new JComboBox(getArrayLugares());
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonVolverASeleccionarPaciente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonVolverASeleccionarPaciente.setText("Volver a Seleccionar Paciente");
        jButtonVolverASeleccionarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverASeleccionarPacienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVolverASeleccionarPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 670, -1, -1));

        jButtonVolverAMenu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonVolverAMenu.setText("Volver a Menu");
        jButtonVolverAMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverAMenuActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVolverAMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 690, -1, -1));

        jLabelNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombre.setText("Nombre");
        getContentPane().add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabelApellido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelApellido.setForeground(new java.awt.Color(255, 255, 255));
        jLabelApellido.setText("Apellido");
        getContentPane().add(jLabelApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabelTelefono.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelTelefono.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTelefono.setText("Telefono");
        getContentPane().add(jLabelTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jLabelDireccion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelDireccion.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDireccion.setText("Direccion");
        getContentPane().add(jLabelDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jLabelLugarDesignado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelLugarDesignado.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLugarDesignado.setText("Lugar Designado");
        getContentPane().add(jLabelLugarDesignado, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));

        jLabelNumero.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelNumero.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNumero.setText("Numero");
        getContentPane().add(jLabelNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, -1, -1));

        jLabelPiso.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelPiso.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPiso.setText("Piso");
        getContentPane().add(jLabelPiso, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        jLabelDepto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelDepto.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDepto.setText("Depto");
        getContentPane().add(jLabelDepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, -1, -1));

        jLabelHistoriaClinica.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelHistoriaClinica.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHistoriaClinica.setText("Historia Clinica");
        getContentPane().add(jLabelHistoriaClinica, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, -1));

        jLabelObservaciones.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelObservaciones.setForeground(new java.awt.Color(255, 255, 255));
        jLabelObservaciones.setText("Observaciones");
        getContentPane().add(jLabelObservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, -1, -1));

        jTextAreaObservaciones.setText(paciente.getObservaciones());
        jTextAreaObservaciones.setColumns(20);
        jTextAreaObservaciones.setRows(5);
        jScrollPane1.setViewportView(jTextAreaObservaciones);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, 278, 130));

        jTextFieldHistoriaClinica.setText(""+paciente.getHistoria_clinica());
        getContentPane().add(jTextFieldHistoriaClinica, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 98, -1));

        jTextFieldLugarDesignado.setEditable(false);
        jTextFieldLugarDesignado.setText(paciente.getLugarDesignado().getNombre());
        getContentPane().add(jTextFieldLugarDesignado, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 98, -1));

        jTextFieldDireccion.setText(paciente.getDireccion().getCalle());
        getContentPane().add(jTextFieldDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 124, -1));

        jTextFieldNombre.setText(paciente.getNombre());
        getContentPane().add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 140, -1));

        jTextFieldTelefono.setText(""+paciente.getTelefono());
        getContentPane().add(jTextFieldTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 140, -1));

        jTextFieldNumero.setText(""+paciente.getDireccion().getNumero());
        getContentPane().add(jTextFieldNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 81, -1));

        jTextFieldPiso.setText(""+paciente.getDireccion().getPiso());
        getContentPane().add(jTextFieldPiso, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 42, -1));

        jTextFieldDepto.setText(paciente.getDireccion().getDepartamento());
        getContentPane().add(jTextFieldDepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 45, -1));

        jTextFieldApellido.setText(paciente.getApellido());
        getContentPane().add(jTextFieldApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 140, -1));

        jButtonGuardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 670, -1, -1));

        jLabelEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelEmail.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEmail.setText("Email");
        getContentPane().add(jLabelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        jTextFieldEmail.setText(paciente.getEmail());
        getContentPane().add(jTextFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 250, -1));

        jComboBoxLugares.setSelectedIndex(indice);
        getContentPane().add(jComboBoxLugares, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ingresar Datos del Paciente");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesL2/FondoNotificacion.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolverASeleccionarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverASeleccionarPacienteActionPerformed
        modificarDatosDePacienteController.volverASeleccionarPaciente(this);
    }//GEN-LAST:event_jButtonVolverASeleccionarPacienteActionPerformed

    private void jButtonVolverAMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverAMenuActionPerformed
        modificarDatosDePacienteController.volverAMenu(this);
    }//GEN-LAST:event_jButtonVolverAMenuActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        guardar();
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    public void guardar(){
        try {
            if ((! jTextFieldNombre.getText().equals("") && (! jTextFieldNombre.getText().equalsIgnoreCase(paciente.getNombre())))){
                paciente.setNombre(jTextFieldNombre.getText());
            }
            if ((! jTextFieldApellido.getText().equals("")) && (! jTextFieldApellido.getText().equalsIgnoreCase(paciente.getApellido()))){
                paciente.setApellido(jTextFieldApellido.getText());
            }
            if ((! jTextFieldTelefono.getText().equals("")) && (paciente.getTelefono() != Long.parseLong(jTextFieldTelefono.getText()))){
                paciente.setTelefono(Long.parseLong(jTextFieldTelefono.getText()));
            }
            if ((! jTextFieldDireccion.getText().equals(""))){
                paciente.getDireccion().setCalle(jTextFieldDireccion.getText());
            }
            if ((! jTextFieldNumero.getText().equals(""))){
                paciente.getDireccion().setNumero(new Integer(jTextFieldNumero.getText()));
            }
            if ((! jTextFieldPiso.getText().equals(""))){
                paciente.getDireccion().setPiso(new Integer(jTextFieldPiso.getText()));
            }
            if ((! jTextFieldDepto.getText().equals("")) && (! paciente.getDireccion().getDepartamento().equalsIgnoreCase(jTextFieldDepto.getText()))){
                paciente.getDireccion().setDepartamento(jTextFieldDepto.getText());
            }
            if ((! jTextFieldEmail.getText().equals("")) && (! paciente.getEmail().equalsIgnoreCase(jTextFieldEmail.getText()))){
                paciente.setEmail(jTextFieldEmail.getText());
            }
            if ((! jTextFieldHistoriaClinica.getText().equals("")) && (paciente.getHistoria_clinica() != new Integer(jTextFieldHistoriaClinica.getText()))){
                paciente.setHistoria_clinica(new Integer(jTextFieldHistoriaClinica.getText()));
            }
            if(!Objects.equals(paciente.getLugarDesignado().getId(), getLugarSeleccionado().getId())){
                paciente.setLugarDesignado(getLugarSeleccionado());
            }
            
            paciente.setObservaciones(jTextAreaObservaciones.getText());

            modificarDatosDePacienteController.guardarEnBD(paciente, paciente.getDireccion(), paciente.getLugarDesignado(), this);
            MiDialogo.mostrar("Los cambios fueron guardados con exito", "Notificacion");
        } catch (BDException ex) {
            ex.printStackTrace();
        }
    }
    
    private String[] getArrayLugares() {
        String[] lugares = new String[lista.size()];
        for(int i=0; i<lista.size();i++) { 
            lugares[i] = lista.get(i).getNombre();
            if (Objects.equals(lista.get(i).getId(), paciente.getLugarDesignado().getId())){
                indice = i;
            }
        }
        return lugares;
    }

    private Lugar getLugarSeleccionado() {
        return lista.get(this.jComboBoxLugares.getSelectedIndex());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonVolverAMenu;
    private javax.swing.JButton jButtonVolverASeleccionarPaciente;
    private javax.swing.JComboBox<String> jComboBoxLugares;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelDepto;
    private javax.swing.JLabel jLabelDireccion;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelHistoriaClinica;
    private javax.swing.JLabel jLabelLugarDesignado;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNumero;
    private javax.swing.JLabel jLabelObservaciones;
    private javax.swing.JLabel jLabelPiso;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaObservaciones;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldDepto;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldHistoriaClinica;
    private javax.swing.JTextField jTextFieldLugarDesignado;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNumero;
    private javax.swing.JTextField jTextFieldPiso;
    private javax.swing.JTextField jTextFieldTelefono;
    // End of variables declaration//GEN-END:variables
}
