/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.tusalud.interfacesEmpleado;

import com.mycompany.tusalud.controller.AgregarCuentaController;
import com.mycompany.tusalud.data.Empleado;
import com.mycompany.tusalud.data.Lugar;
import com.mycompany.tusalud.db.LugarService;
import com.mycompany.tusalud.excepciones.BDException;
import com.mycompany.tusalud.excepciones.TuSaludException;
import com.mycompany.tusalud.interfaces.MiDialogo;
import java.util.List;
import javax.swing.JComboBox;

/**
 *
 * @author Alumno
 */
public class VistaAgregarEmpleado extends javax.swing.JFrame {

    AgregarCuentaController agregarCuentaController;
    private LugarService lugarService = new LugarService();
    private List<Lugar> lista;
    
    /**
     * Creates new form AgregarEmpleado2
     * @param agregarCuentaController
     */
    public VistaAgregarEmpleado(AgregarCuentaController agregarCuentaController) throws BDException {
        this.agregarCuentaController = agregarCuentaController;       
        this.lista = lugarService.getListaDeLugares();
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsuario = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        lblNroLegajo = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        textUsuario = new javax.swing.JTextField();
        textContraseña = new javax.swing.JTextField();
        textNombre = new javax.swing.JTextField();
        textApellido = new javax.swing.JTextField();
        textNroLegajo = new javax.swing.JTextField();
        textEmail = new javax.swing.JTextField();
        textDireccion = new javax.swing.JTextField();
        lblCalle = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        lblPiso = new javax.swing.JLabel();
        lblDepto = new javax.swing.JLabel();
        textNumero = new javax.swing.JTextField();
        textPiso = new javax.swing.JTextField();
        textDepto = new javax.swing.JTextField();
        lblLigares = new javax.swing.JLabel();
        jcLugares = new JComboBox(getArrayLugares());
        jButtonAgregar = new javax.swing.JButton();
        jButtonAtras = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUsuario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setText("Usuario");
        getContentPane().add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        lblContraseña.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblContraseña.setForeground(new java.awt.Color(255, 255, 255));
        lblContraseña.setText("Contraseña");
        getContentPane().add(lblContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        lblNombre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Nombre");
        getContentPane().add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        lblApellido.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblApellido.setForeground(new java.awt.Color(255, 255, 255));
        lblApellido.setText("Apellido");
        getContentPane().add(lblApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        lblNroLegajo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblNroLegajo.setForeground(new java.awt.Color(255, 255, 255));
        lblNroLegajo.setText("Nro Legajo");
        getContentPane().add(lblNroLegajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        lblEmail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("Email");
        getContentPane().add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        lblDireccion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblDireccion.setForeground(new java.awt.Color(255, 255, 255));
        lblDireccion.setText("Direccion");
        getContentPane().add(lblDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, -1, -1));
        getContentPane().add(textUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 104, -1));
        getContentPane().add(textContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 104, -1));
        getContentPane().add(textNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 104, -1));
        getContentPane().add(textApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 104, -1));
        getContentPane().add(textNroLegajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 104, -1));
        getContentPane().add(textEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 104, -1));
        getContentPane().add(textDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 114, -1));

        lblCalle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCalle.setForeground(new java.awt.Color(255, 255, 255));
        lblCalle.setText("Calle");
        getContentPane().add(lblCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, -1, -1));

        lblNumero.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblNumero.setForeground(new java.awt.Color(255, 255, 255));
        lblNumero.setText("Numero");
        getContentPane().add(lblNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, -1, -1));

        lblPiso.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblPiso.setForeground(new java.awt.Color(255, 255, 255));
        lblPiso.setText("Piso");
        getContentPane().add(lblPiso, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 440, -1, -1));

        lblDepto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblDepto.setForeground(new java.awt.Color(255, 255, 255));
        lblDepto.setText("Depto");
        getContentPane().add(lblDepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 440, -1, -1));

        textNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNumeroActionPerformed(evt);
            }
        });
        getContentPane().add(textNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, 80, -1));

        textPiso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPisoActionPerformed(evt);
            }
        });
        getContentPane().add(textPiso, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, 36, -1));

        textDepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDeptoActionPerformed(evt);
            }
        });
        getContentPane().add(textDepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 470, 35, -1));

        lblLigares.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblLigares.setForeground(new java.awt.Color(255, 255, 255));
        lblLigares.setText("Seleccione Lugar de Atencion");
        getContentPane().add(lblLigares, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, -1, -1));

        jcLugares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcLugaresActionPerformed(evt);
            }
        });
        getContentPane().add(jcLugares, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 560, 121, -1));

        jButtonAgregar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonAgregar.setText("Agregar");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 640, -1, -1));

        jButtonAtras.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonAtras.setText("Atras");
        jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 670, 80, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Agregar Empleado");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesL2/FondoNotificacion.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(400, 450));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        registrar();
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed
        volverAMenu();
    }//GEN-LAST:event_jButtonAtrasActionPerformed

    private void textNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNumeroActionPerformed

    private void jcLugaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcLugaresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcLugaresActionPerformed

    private void textPisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPisoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPisoActionPerformed

    private void textDeptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDeptoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDeptoActionPerformed

    private void registrar() {
        
        String nombre, apellido, usuario, contraseña,email,calle,depto;

        int numLegajo,numero,piso;
        try {
            numLegajo = new Integer(textNroLegajo.getText());
        } catch (Exception e) {
            MiDialogo.mostrar("Error", "Legajo debe ser un valor numerico");
            return;
        }
         try {
            numero = new Integer(textNumero.getText());
            piso=new Integer(textPiso.getText());
        } catch (Exception e) {
            MiDialogo.mostrar("Error", "Debe ser un valor numerico");
            return;
        }
        nombre = textNombre.getText();
        apellido = textApellido.getText();
        usuario = textUsuario.getText();
        contraseña = textContraseña.getText();
        email=textEmail.getText();
        calle=textDireccion.getText();
        depto=textDepto.getText();        
        Lugar lugar = getLugarSeleccionado();
        
        try {
          Empleado  empleado = agregarCuentaController.AgregarCuentaEmpleado(nombre, apellido, numero, email, calle, numero, piso, depto, numLegajo, lugar, usuario, contraseña);
        } catch (TuSaludException ex) {
            MiDialogo.mostrar(ex, "Error al crear el Empleado");
            return;
        }
        MiDialogo.mostrar("Su cuenta fue creada con Exito", "Bienvenido!!!");
        volverAMenu();
    }  
    
    private String[] getArrayLugares() {
        String[] lugares = new String[lista.size()];
        for(int i=0; i<lista.size();i++) { 
            lugares[i] = lista.get(i).getNombre();
        }
        return lugares;
    }
    
    private void volverAMenu() {
        agregarCuentaController.volverAMenu(this);
    }

    private Lugar getLugarSeleccionado() {
        return lista.get(this.jcLugares.getSelectedIndex());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> jcLugares;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblCalle;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblDepto;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblLigares;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNroLegajo;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblPiso;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField textApellido;
    private javax.swing.JTextField textContraseña;
    private javax.swing.JTextField textDepto;
    private javax.swing.JTextField textDireccion;
    private javax.swing.JTextField textEmail;
    private javax.swing.JTextField textNombre;
    private javax.swing.JTextField textNroLegajo;
    private javax.swing.JTextField textNumero;
    private javax.swing.JTextField textPiso;
    private javax.swing.JTextField textUsuario;
    // End of variables declaration//GEN-END:variables
}
