/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.tusalud.interfacesEmpleado;

import com.mycompany.tusalud.controllerEmpleado.PacientesDeLugarController;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JFrame;

/**
 *
 * @author Alumno
 */
public class VistaPacientesDeLugar extends javax.swing.JFrame {

    PacientesDeLugarController pacientesDeLugarController;
    private Map<Integer, Integer> tablaBotonPaciente = new HashMap<>();
    private List<Object[]> lista;
    
    /**
     * Creates new form VistaPacientesDeLugar
     * @param pacientesDeLugarController
     * @param lista
     */
    public VistaPacientesDeLugar(PacientesDeLugarController pacientesDeLugarController, List<Object[]> lista) {
        this.pacientesDeLugarController = pacientesDeLugarController;
        this.lista = lista;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonSeleccionarPaciente = new javax.swing.JButton();
        jButtonVolverANotificaciones = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldIndice = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(650, 750));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            getMatrizObject(getArregloString().length),
            getArregloString()
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 420, 350));

        jButtonSeleccionarPaciente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSeleccionarPaciente.setText("Seleccionar Paciente");
        jButtonSeleccionarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeleccionarPacienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSeleccionarPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, -1, -1));

        jButtonVolverANotificaciones.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonVolverANotificaciones.setText("Volver a Notificaciones");
        jButtonVolverANotificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverANotificacionesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVolverANotificaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 550, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pacientes");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));
        getContentPane().add(jTextFieldIndice, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 130, -1));

        jButtonBuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 130, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesL2/FondoNotificacion.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolverANotificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverANotificacionesActionPerformed
        pacientesDeLugarController.volverANotificacionGlobal(this);
    }//GEN-LAST:event_jButtonVolverANotificacionesActionPerformed

    private void jButtonSeleccionarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeleccionarPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSeleccionarPacienteActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        pacientesDeLugarController.buscarPacientePorIndice(jTextFieldIndice.getText()+"%", this);
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private Object[][] getMatrizObject(Integer tamaño){
        Object[][] matriz = new Object[lista.size()][tamaño];
        
        for(int fila=0; fila<lista.size(); fila++){
            
            matriz[fila][0] = lista.get(fila)[1];
            matriz[fila][1] = lista.get(fila)[2];
            matriz[fila][2] = lista.get(fila)[3];
            matriz[fila][3] = lista.get(fila)[4];
            
            tablaBotonPaciente.put(fila, (Integer) lista.get(fila)[0]);
        }
        
        jButtonSeleccionarPaciente.addActionListener(listenerBoton);
        
        return matriz;
    }
    
    private String[] getArregloString(){
        String[] arreglo = {"Apellido", "Nombre", "Historia Clinica", "Telefono"};
        
        return arreglo;
    }
    
    private ActionListener listenerBoton = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent ae) {
            Integer idPaciente = tablaBotonPaciente.get(jTable1.getSelectedRow());
            if(idPaciente != null){
                pacientesDeLugarController.CargarNotificacionesDePaciente(idPaciente, estaVentana());
            }
            else{
                System.out.println("No ha seleccionado paciente");
            }
        }
    };
    
    private JFrame estaVentana(){
        return this;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonSeleccionarPaciente;
    private javax.swing.JButton jButtonVolverANotificaciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldIndice;
    // End of variables declaration//GEN-END:variables
}
