/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.tusalud.interfacesEmpleado;

import com.mycompany.tusalud.controllerEmpleado.NotificacionGlobalController;
import com.mycompany.tusalud.excepciones.BDException;
import com.mycompany.tusalud.interfaces.MiDialogo;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 *
 * @author Alumno
 */
public class VistaNotificacionGlobal extends javax.swing.JFrame {

    NotificacionGlobalController notificacionGlobalController;
    private Map<Integer, String> tablaBotonStringNotificacion = new HashMap<>();
    private Map<Integer, Integer> tablaBotonIdNotificacion = new HashMap<>();
    List<Object[]> lista;
    
    /**
     * Creates new form NewJFrame
     * @param notificacionGlobalController
     * @param lista
     */
    public VistaNotificacionGlobal(NotificacionGlobalController notificacionGlobalController, List<Object[]> lista) {
        this.notificacionGlobalController =  notificacionGlobalController;
        this.lista = lista;
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    private ActionListener listenerBoton = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent ae) {
            String mensaje = tablaBotonStringNotificacion.get(jTable1.getSelectedRow());
            if(mensaje != null){
                notificacionGlobalController.mostrarMensaje(mensaje);
            }
            else{
                System.out.println("No ha seleccionado notificacion");
            }
        }
    };
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonVolverAMenu = new javax.swing.JButton();
        jButtonVerMensaje = new javax.swing.JButton();
        jButtonAgregarNotificacion = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButtonEliminarNotificacion = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            getMatrizObject(getArregloString().length),
            getArregloString()
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 430, 420));

        jButtonVolverAMenu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonVolverAMenu.setText("Volver a Menu");
        jButtonVolverAMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverAMenuActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVolverAMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 660, 167, -1));

        jButtonVerMensaje.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonVerMensaje.setText("Ver Mensaje");
        getContentPane().add(jButtonVerMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 620, 200, -1));

        jButtonAgregarNotificacion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonAgregarNotificacion.setText("Agregar Notificacion");
        jButtonAgregarNotificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarNotificacionActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAgregarNotificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 200, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Notificacion de Paciente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 570, 200, -1));

        jButtonEliminarNotificacion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonEliminarNotificacion.setText("Eliminar Notificacion");
        jButtonEliminarNotificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarNotificacionActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEliminarNotificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 620, 200, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setText("Notificacion Global");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesL2/FondoNotificacion.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 650, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolverAMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverAMenuActionPerformed
        cerrar();
    }//GEN-LAST:event_jButtonVolverAMenuActionPerformed

    private void jButtonAgregarNotificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarNotificacionActionPerformed
        notificacionGlobalController.crearNotificaciones(this);
    }//GEN-LAST:event_jButtonAgregarNotificacionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        notificacionGlobalController.crearNotificacionesDePaciente(this);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonEliminarNotificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarNotificacionActionPerformed
        Integer id = tablaBotonIdNotificacion.get(jTable1.getSelectedRow());
        try {
            if(id != null){
                notificacionGlobalController.eliminarNotificacion(id, this);
                MiDialogo.mostrar("Notificacion eliminada", "Notificacion");
            }
            else{
                System.out.println("No se ha seleccionado Notificacion");
            }
        } catch (BDException ex) {
            MiDialogo.mostrar(ex, "Error al eliminar la Notificacion");
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButtonEliminarNotificacionActionPerformed

    private Object[][] getMatrizObject(Integer tamaño){
        Object[][] matriz = new Object[lista.size()][tamaño];
        
        for(int fila=0; fila<lista.size(); fila++){
            
            for(int columna=0; columna<tamaño; columna++){
                matriz[fila][columna] = lista.get(fila)[columna+1];
            }
            
            tablaBotonStringNotificacion.put(fila, (String) lista.get(fila)[3]);
            tablaBotonIdNotificacion.put(fila, (Integer) lista.get(fila)[0]);
        }
        
        jButtonVerMensaje.addActionListener(listenerBoton);
        
        return matriz;
    }
    
    private String[] getArregloString(){
        String[] arreglo = {"FechaVigenciaInicial", "FechaVigenciaFinal", "Texto"};
        
        return arreglo;
    }
    
    public String getNombreDeLugar(){
        return notificacionGlobalController.getLugar().getNombre();
    }
    
    public void cerrar() {
        notificacionGlobalController.volverAMenu(this);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAgregarNotificacion;
    private javax.swing.JButton jButtonEliminarNotificacion;
    private javax.swing.JButton jButtonVerMensaje;
    private javax.swing.JButton jButtonVolverAMenu;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
