/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.tusalud.interfacesEmpleado;

import com.mycompany.tusalud.controllerEmpleado.CrearNotificacionController;
import com.mycompany.tusalud.data.Lugar;
import com.mycompany.tusalud.data.Paciente;
import com.mycompany.tusalud.interfaces.MiDialogo;
import java.sql.Date;
import java.time.LocalDate;

/**
 *
 * @author Alumno
 */
public class VistaCrearNotificacion extends javax.swing.JFrame {

    CrearNotificacionController crearNotificacionController;
    private Paciente paciente;
    private Lugar lugar;
    
    /**
     * Creates new form VistaCrearNotificacion
     * @param crearNotificacionController
     * @param paciente
     * @param lugar
     */
    public VistaCrearNotificacion(CrearNotificacionController crearNotificacionController, Paciente paciente, Lugar lugar) {
        this.crearNotificacionController = crearNotificacionController;
        this.paciente = paciente;
        this.lugar = lugar;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabelFechaVigenciaInicial = new javax.swing.JLabel();
        jTextFieldAñoInicial = new javax.swing.JTextField();
        jTextFieldMesInicial = new javax.swing.JTextField();
        jTextFieldDiaInicial = new javax.swing.JTextField();
        jLabelFechaVigenciaFinal = new javax.swing.JLabel();
        jTextFieldAñoFinal = new javax.swing.JTextField();
        jTextFieldMesFinal = new javax.swing.JTextField();
        jTextFieldDiaFinal = new javax.swing.JTextField();
        jLabelMensaje = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaMensaje = new javax.swing.JTextArea();
        jButtonGuardarNotificacion = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Crear Notificaciones ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 390, -1));

        jLabelFechaVigenciaInicial.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelFechaVigenciaInicial.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFechaVigenciaInicial.setText("FechaVigenciaInicial");
        getContentPane().add(jLabelFechaVigenciaInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));
        getContentPane().add(jTextFieldAñoInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 42, -1));
        getContentPane().add(jTextFieldMesInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 29, -1));
        getContentPane().add(jTextFieldDiaInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 30, -1));

        jLabelFechaVigenciaFinal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelFechaVigenciaFinal.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFechaVigenciaFinal.setText("FechaVigenciaFinal");
        getContentPane().add(jLabelFechaVigenciaFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jTextFieldAñoFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAñoFinalActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldAñoFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 42, -1));
        getContentPane().add(jTextFieldMesFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 29, -1));
        getContentPane().add(jTextFieldDiaFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 30, -1));

        jLabelMensaje.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelMensaje.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMensaje.setText("Mensaje");
        getContentPane().add(jLabelMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 336, 80, 30));

        jTextAreaMensaje.setColumns(20);
        jTextAreaMensaje.setRows(5);
        jScrollPane1.setViewportView(jTextAreaMensaje);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, -1, -1));

        jButtonGuardarNotificacion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonGuardarNotificacion.setText("Guardar Notificacion");
        jButtonGuardarNotificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarNotificacionActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGuardarNotificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, -1, -1));

        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 580, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesL2/FondoNotificacion.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarNotificacion(){
        try{
            Date fechaVigenciaInicial = Date.valueOf(LocalDate.of(new Integer(jTextFieldAñoInicial.getText()), new Integer(jTextFieldMesInicial.getText()), new Integer(jTextFieldDiaInicial.getText())));
            Date fechaVigenciaFinal = Date.valueOf(LocalDate.of(new Integer(jTextFieldAñoFinal.getText()), new Integer(jTextFieldMesFinal.getText()), new Integer(jTextFieldDiaFinal.getText())));
            String texto = jTextAreaMensaje.getText();

            if((fechaVigenciaInicial == null) | (fechaVigenciaFinal == null)){
                MiDialogo.mostrar("Faltan completar campos", "Error");
            }
            else{
                crearNotificacionController.crearNotificacion(fechaVigenciaInicial, fechaVigenciaFinal, texto, paciente, lugar, this);
                MiDialogo.mostrar("La notificacion fue creada con exito", "Notificacion");
            }
        } catch(NumberFormatException e){
            MiDialogo.mostrar("Ingrese una fecha valida", "Error");
        }
    }
    
    private void jButtonGuardarNotificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarNotificacionActionPerformed
        guardarNotificacion();
    }//GEN-LAST:event_jButtonGuardarNotificacionActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        crearNotificacionController.volverACargarNotificaciones(paciente, this);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTextFieldAñoFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAñoFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAñoFinalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonGuardarNotificacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelFechaVigenciaFinal;
    private javax.swing.JLabel jLabelFechaVigenciaInicial;
    private javax.swing.JLabel jLabelMensaje;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaMensaje;
    private javax.swing.JTextField jTextFieldAñoFinal;
    private javax.swing.JTextField jTextFieldAñoInicial;
    private javax.swing.JTextField jTextFieldDiaFinal;
    private javax.swing.JTextField jTextFieldDiaInicial;
    private javax.swing.JTextField jTextFieldMesFinal;
    private javax.swing.JTextField jTextFieldMesInicial;
    // End of variables declaration//GEN-END:variables
}
